"""T041: Copy the 19 Market Manager dimensions from hipstraw-faculty/seed_data/grammar.json
into config/grammar.yaml with U+FFFD replacement character scrubbing.

Usage:
  python scripts/copy_grammar.py PATH_TO_GRAMMAR_JSON [--out config/grammar.yaml]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import date
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]

HEADER = """# Generated by scripts/copy_grammar.py on {today} (T041).
# Source: {source_path}
# SHA-256: {sha256}
# U+FFFD replacement characters removed: {fffd_count}

"""


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="path to grammar.json from hipstraw-faculty")
    parser.add_argument("--out", type=Path, default=ROOT / "config" / "grammar.yaml")
    args = parser.parse_args(argv)

    raw_bytes = args.source.read_bytes()
    sha256 = hashlib.sha256(raw_bytes).hexdigest()

    raw_text = raw_bytes.decode("utf-8")
    fffd_count = raw_text.count("�")
    clean_text = raw_text.replace("�", "–")  # en dash

    dimensions = json.loads(clean_text)
    if not isinstance(dimensions, list):
        print(f"error: expected a JSON array, got {type(dimensions).__name__}", file=sys.stderr)
        return 1

    for dim in dimensions:
        if dim.get("decidedBy") != "market_manager":
            print(f"warning: dimension {dim.get('key')!r} has decidedBy={dim.get('decidedBy')!r}", file=sys.stderr)

    data = {"dimensions": dimensions}

    header = HEADER.format(
        today=date.today().isoformat(),
        source_path=args.source,
        sha256=sha256,
        fffd_count=fffd_count,
    )
    body = yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=120)
    args.out.write_text(header + body, encoding="utf-8")
    print(f"wrote {len(dimensions)} dimensions to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
